[[component]]
name = "button-escape"

draw = "ui-rect"
x = -64
y = 64
width = 48
height = 48
origin-x = 1.0
origin-y = -1.0

interact = "button"
gamepad = "b9"
keyboard = "esc"
action = [
    ["resetview"],
]