[[component]]
name = "button-inventory-next"

draw = "ui-rect"
x = 128
y = 160
width = 32
height = 32
origin-x = -1.0
origin-y = 0.0

interact = "button"
gamepad = "rb"
keyboard = "e"
action = [
    ["inventory_next"],
]