[[component]]
name = "inventory"

draw = "inventory"
x = 128
y = 0
width = 256
height = 256
origin-x = -1.0
origin-y = 0.0

interact = "always"
action = [
    ["inventory"],
]

[component.text]
contents = ""

[[draw]]
name = "inventory"
mesh = "rect"
shader = "mesh-pt"
ortho = true
alpha = true
