[[tile]]
name = "dirt-tile"
text = "タイル"
desc = "何の変哲もない足場"
draw = "dirt-tile"
save-id = 100

[[draw]]
name = "dirt-tile"
mesh = "tile"
shader = "mesh-pt"
image = "tile"
depth = true

[[image]]
name = "tile"
src = "tile.png"
