[[tile]]
name = "mine"
text = "鉱物"
desc = "素材が採掘できる岩場"
draw = "mine"
height = 5
save-id = 2

[[draw]]
name = "mine"
mesh = "mine"
shader = "mesh_pt"
texture = "mine"
depth = true

[[mesh]]
name = "mine"
position = [
  0.0, 0.0, 0.0,
  2.0, 0.0, 0.0,
  0.0, 2.0, 0.0,
  2.0, 2.0, 0.0,
  0.0, 0.0, 2.5,
  2.0, 0.0, 2.5,
  0.0, 2.0, 2.5,
  2.0, 2.0, 2.5,
]
color = [
  32, 32, 32, 255,
  32, 32, 32, 255,
  32, 32, 32, 255,
  32, 32, 32, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
]
uv = [
    0.0, 0.0,
    1.0, 0.0,
    0.0, 1.0,
    1.0, 1.0,
    0.25, 0.25,
    0.75, 0.25,
    0.25, 0.75,
    0.75, 0.75,
]
index = [
  0, 1, 2,
  2, 1, 3,
  1, 5, 3,
  3, 5, 7,
  5, 4, 7,
  7, 4, 6,
  4, 0, 6,
  6, 0, 2,
  2, 3, 6,
  6, 3, 7,
  5, 1, 4,
  4, 1, 0,
]

[[texture]]
name = "mine"
src = "mine.png"
