[[tile]]
name = "tile"
text = "タイル"
desc = "何の変哲もない足場"
draw = "tile"
height = 1
save-id = 100

[[draw]]
name = "tile"
mesh = "tile"
shader = "mesh-pt"
image = "tile"
depth = true

[[mesh]]
name = "tile"
position = [
  0.0, 0.0, 0.0,
  2.0, 0.0, 0.0,
  0.0, 2.0, 0.0,
  2.0, 2.0, 0.0,
  0.0, 0.0, 0.5,
  2.0, 0.0, 0.5,
  0.0, 2.0, 0.5,
  2.0, 2.0, 0.5,
]
color = [
  32, 32, 32, 255,
  32, 32, 32, 255,
  32, 32, 32, 255,
  32, 32, 32, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
  64, 64, 64, 255,
]
uv = [
    0.0, 0.0,
    1.0, 0.0,
    0.0, 1.0,
    1.0, 1.0,
    0.25, 0.25,
    0.75, 0.25,
    0.25, 0.75,
    0.75, 0.75,
]
index = [
  0, 1, 2,
  2, 1, 3,
  1, 5, 3,
  3, 5, 7,
  5, 4, 7,
  7, 4, 6,
  4, 0, 6,
  6, 0, 2,
  2, 3, 6,
  6, 3, 7,
  5, 1, 4,
  4, 1, 0,
]

[[image]]
name = "tile"
src = "tile.png"
