[[com]]
name = "activate-target"

[com.rect]
draw = "ui-rect"
x = 0
y = -24
width = 512
height = 20
origin-x = 0.0
origin-y = 1.0

[com.text]
contents = ""

[com.tick]
action = [
    ["activate-target"],
]
