[[com]]
name = "button-activate"

[com.rect]
draw = "ui-rect"
x = -256
y = -128
width = 48
height = 48
origin-x = 1.0
origin-y = 1.0

[com.touch]
gamepad = "b0"
keyboard = "space"
action = [
    ["activate"],
]
