[[com]]
name = "button-inventory-next"

[com.rect]
draw = "ui-rect"
x = 60
y = -148
width = 32
height = 32
origin-x = -1.0
origin-y = 0.0

[com.touch]
gamepad = "rb"
keyboard = "e"
action = [
  ["inventory_next"],
]
