[[com]]
name = "button-off-hand"

[com.rect]
draw = "ui-rect"
x = 256
y = -64
width = 48
height = 48
origin-x = -1.0
origin-y = 1.0

[com.touch]
gamepad = "lt"
keyboard = "c"
action = [
  ["off-hand"],
]
