[[com]]
name = "button-inventory-prev"

draw = "ui-rect"
x = 24
y = -148
width = 32
height = 32
origin-x = -1.0
origin-y = 0.0

interact = "button"
gamepad = "lb"
keyboard = "q"
action = [
    ["inventory_prev"],
]