[[com]]
name = "button-escape"

[com.rect]
draw = "ui-rect"
x = -64
y = 64
width = 48
height = 48
origin-x = 1.0
origin-y = -1.0

[com.touch]
gamepad = "b9"
keyboard = "esc"
action = [
    ["resetview"],
]
