title = "Demo"
addr = ":8080"
logging = false
assert = false
minify = true

[ui-layout]
pause = [
    "button-newgame",
    "button-loadgame",
]
main = [
    "reticle",
    "button-act",
    "button-sub",
    "button-escape",
    "left-stick",
    "right-stick",
]
