title = "Demo"
addr = ":8080"
logging = false
assert = false
minify = true
initial-view = "pause"

[[view]]
name = "pause"
ui = [
    "button-newgame",
    "button-loadgame",    
]
event = [
    "newgame",
    "loadgame",
]

[[view]]
name = "main"
draw3d = true
ui = [
    "reticle",
    "button-act",
    "button-sub",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "movement",
    "act",
    "sub",
    "escape",
]

script = []
