[[component]]
name = "button-loadgame"

draw = "ui-loadgame"
x = 160
y = 0
width = 256
height = 256

interact = "button"
gamepad = "b9"
keyboard = "x"
action = [
    ["loadgame", "slot0"],
    ["nextview", "main"],
]

[component.text]
contents = "Load Game"

[[draw]]
name = "ui-loadgame"
mesh = "rect"
shader = "mesh-pt"
ortho = true
