[[component]]
name = "button-newgame"

draw = "ui-newgame"
x = -160
y = 0
width = 256
height = 256

interact = "button"
gamepad = "b8"
keyboard = "z"
action = [
    ["newgame", "slot0"],
    ["makeworld"],
    ["nextview", "main"],
]

[component.text]
contents = "New Game"

[[draw]]
name = "ui-newgame"
mesh = "rect"
shader = "mesh-pt"
ortho = true
