[[tile]]
name = "rock-mine"
text = "石の山"
desc = "石が採掘できる山場"
draw = "rock-mine"
save-id = 200

[tile.mine]
item = "rock"
count = 10

[[draw]]
name = "rock-mine"
mesh = "mine"
shader = "mesh-pt"
image = "rock"
depth = true

[[image]]
name = "rock"
src = "rock.png"
