[[view]]
name = "main"
draw3d = true
camera-mob = "player"
draw = [
  "skybox",
]
com = [
  # movement
  "left-stick",
  "right-stick",

  # inventory
  "button-inventory-prev",
  "button-inventory-next",
  "inventory",

  # hand
  "button-hand",

  # activate
  "button-activate",
  "activate-target",

  # misc
  "button-escape",
]
