[[view]]
name = "main"
draw3d = true
draw = [
    "skybox",
]
com = [
    # movement
    "left-stick",
    "right-stick",
    "movement",

    # inventory
    "button-inventory-prev",
    "button-inventory-next",
    "inventory",

    # hand
    "button-hand",
    "button-off-hand",

    # activate
    "button-activate",
    "activate-target",

    # misc
    "button-escape",
]