[[view]]
name = "main"
draw3d = true
skybox = "skybox"
ui = [
    "inventory",
    "button-inventory-prev",
    "button-inventory-next",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "inventory",
    "inventory-prev",
    "inventory-next",
    "movement",
    "escape",
]