[[view]]
name = "main"
draw3d = true
skybox = "skybox"
component = [
    # movement
    "left-stick",
    "right-stick",
    "movement",

    # inventory
    "button-inventory-prev",
    "button-inventory-next",
    "inventory",

    # activate
    "activate",

    # misc
    "button-escape",
]