[[view]]
name = "main"
com = [
  # movement
  "left-stick",
  "right-stick",

  # inventory
  "button-inventory-prev",
  "button-inventory-next",
  "inventory",

  # hand
  "button-hand",

  # activate
  "button-activate",
  "activate-target",

  # misc
  "button-giveup",

  "gameover",
]

[view.grid]
camera-mob = "player"
draw = [
  "skybox",
]