[[base]]
name = "dirt"
draw = "base-dirt"
save-id = 100

[[draw]]
name = "base-dirt"
mesh = "base"
shader = "mesh-pt"
image = "dirt"
state = { depth = true }

[[image]]
name = "dirt"
src = "img/dirt.png"
