[[mob]]
name = "slug"
draw = "slug"

[[draw]]
name = "slug"
mesh = "slug"
shader = "mesh-pc"
depth = true

[[mesh]]
name = "slug"
position = [
  -0.8, -0.4, 0.0,
  +0.8, -0.4, 0.0,
  -0.8, +0.4, 0.0,
  +0.8, +0.4, 0.0,
  +0.6, 0.0, 0.8,
]
color = [
  210, 180, 140, 255,
  210, 180, 140, 255,
  210, 180, 140, 255,
  210, 180, 140, 255,
]
index = [
  2, 4, 0,
  0, 4, 1,
  1, 4, 3,
  3, 4, 2,
]