[[mob]]
name = "slug"
draw = "slug"
radius = 0.4
mass = 0.5
hp = 1

[[draw]]
name = "slug"
mesh = "slug"
shader = "mesh-pc"
state = { depth = true }

[[mesh]]
name = "slug"

[mesh.buffer]
position = [
  -0.8, -0.4, 0.0,
  +0.8, -0.4, 0.0,
  -0.8, +0.4, 0.0,
  +0.8, +0.4, 0.0,
  +0.6, 0.0, 0.8,
]
color = [
  210, 180, 140, 255,
  210, 180, 140, 255,
  210, 180, 140, 255,
  210, 180, 140, 255,
]
index = [
  2, 4, 0,
  0, 4, 1,
  1, 4, 3,
  3, 4, 2,
]
view = [
  { mode = 3, start = 0, count = 12 },
]
