
[[shader]]
name = "mesh-p"
vertex-shader = """
#version 300 es
layout (location = 0) in vec3 p;
uniform mat4 w;
uniform mat4 vp;
void main() {
  gl_Position = vp * w * vec4(p, 1);
}
"""
fragment-shader = """
#version 300 es
precision mediump float;
out vec4 fc;
void main() {
  fc = vec4(0.8, 0.8, 0.8, 1.0);
}
"""
uniform = ["w", "vp"]

[[shader]]
name = "mesh-pc"
vertex-shader = """
#version 300 es
layout (location = 0) in vec3 p;
layout (location = 2) in vec4 c;
uniform mat4 w;
uniform mat4 vp;
out vec4 vc;
void main() {
  gl_Position = vp * w * vec4(p, 1);
  vc = c;
}
"""
fragment-shader = """
#version 300 es
precision mediump float;
in vec4 vc;
out vec4 fc;
void main() {
  fc = vc;
}
"""
uniform = ["w", "vp"]

[[shader]]
name = "mesh-pt"
vertex-shader = """
#version 300 es
layout (location = 0) in vec3 p;
layout (location = 3) in vec2 uv;
uniform mat4 w;
uniform mat4 vp;
out vec2 vu;
void main() {
  gl_Position = vp * w * vec4(p, 1);
  vu = uv;
}
"""
fragment-shader = """
#version 300 es
precision mediump float;
in vec2 vu;
uniform sampler2D tex0;
out vec4 fc;
void main() {
  fc = texture(tex0, vu);
}
"""
uniform = ["w", "vp", "tex0"]
