
[[draw]]
name = "skybox"
mesh = "skybox"
shader = "mesh_pc"

[[draw]]
name = "stack"
mesh = "stack"
shader = "mesh_pc"
depth = true

[[draw]]
name = "ui-reticle"
mesh = "reticle"
shader = "mesh_pc"
ortho = true

[[draw]]
name = "ui-rect"
mesh = "rect"
shader = "mesh_pc"
ortho = true

[[stack]]
id = 1
draw = "stack"
height = 1

[[mesh]]
name = "skybox"
position = [
  -1.0, -1.0, -1.0,
  +1.0, -1.0, -1.0,
  -1.0, +1.0, -1.0,
  +1.0, +1.0, -1.0,
  -1.0, -1.0, +1.0,
  +1.0, -1.0, +1.0,
  -1.0, +1.0, +1.0,
  +1.0, +1.0, +1.0,
]
color = [
  8, 8, 8, 255,
  8, 8, 8, 255,
  8, 8, 8, 255,
  8, 8, 8, 255,
  180, 200, 240, 255,
  180, 200, 240, 255,
  180, 200, 240, 255,
  180, 200, 240, 255,
]
index = [
  0, 2, 1,
  1, 2, 3,
  1, 3, 5,
  5, 3, 7,
  5, 7, 4,
  4, 7, 6,
  4, 6, 0,
  0, 6, 2,
  2, 6, 3,
  3, 6, 7,
  5, 4, 1,
  1, 4, 0,
]
