
[[stack]]
id = 1
mesh = "stack"
shader = "mesh_pc"
height = 1

[[ui]]
mesh = "reticle"
shader = "mesh_pc"
width = 8
height = 8

[[ui]]
name = "button_act"
mesh = "rect"
shader = "mesh_pc"
width = 48
height = 48
offset = [-50,0]
interact = "button"
gamepad = "b0"
keyboard = "z"

[[ui]]
name = "button_sub"
mesh = "rect"
shader = "mesh_pc"
width = 48
height = 48
offset = [50,0]
interact = "button"
gamepad = "b1"
keyboard = "x"
