
[[ui]]
name = "reticle"
draw = "ui-reticle"
width = 8
height = 8

[[ui]]
name = "button-act"
draw = "ui-rect"
width = 48
height = 48
offset = [-50,0]
interact = "button"
gamepad = "b0"
keyboard = "z"

[[ui]]
name = "button-sub"
draw = "ui-rect"
width = 48
height = 48
offset = [50,0]
interact = "button"
gamepad = "b1"
keyboard = "x"

[[ui]]
name = "left-stick"
draw = "ui-rect"
width = 96
height = 96
offset = [-200,0]
interact = "left-stick"

[[ui]]
name = "right-stick"
draw = "ui-rect"
width = 96
height = 96
offset = [200,0]
interact = "right-stick"

[[ui]]
name = "button-escape"
draw = "ui-rect"
width = 48
height = 48
offset = [0,200]
interact = "button"
gamepad = "b9"
keyboard = "esc"

[[event]]
name = "movement"
trigger = "always"
action = [
    ["fpsmove", "left-stick", "right-stick"],
]

[[event]]
name = "act"
trigger = "button"
target = "button-act"
action = [
    ["pushstack"],
    ["savegame"],
]

[[event]]
name = "sub"
trigger = "button"
target = "button-sub"
action = [
    ["popstack"],
    ["savegame"],
]

[[event]]
name = "escape"
trigger = "button"
target = "button-escape"
action = [
    ["resetview"],
]

[[view]]
name = "main"
draw3d = true
skybox = "skybox"
ui = [
    "reticle",
    "button-act",
    "button-sub",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "movement",
    "act",
    "sub",
    "escape",
]
