
[[texture]]
name = "tex-counter"
[texture.canvas]
width = 256
height = 64

[[draw]]
name = "ui-counter"
mesh = "rect"
shader = "mesh_pt"
texture = "tex-counter"
ortho = true
alpha = true

[[ui]]
name = "counter"
draw = "ui-counter"
width = 256
height = 64
offset = [0,-160]

[[ui]]
name = "left-stick"
draw = "ui-rect"
width = 96
height = 96
offset = [-200,0]
interact = "left-stick"

[[ui]]
name = "right-stick"
draw = "ui-rect"
width = 96
height = 96
offset = [200,0]
interact = "right-stick"

[[ui]]
name = "button-escape"
draw = "ui-rect"
width = 48
height = 48
offset = [0,200]
interact = "button"
gamepad = "b9"
keyboard = "esc"

[[event]]
name = "update-counter"
trigger = "always"
action = [
    ["text", "tex-counter"],
]

[[event]]
name = "movement"
trigger = "always"
action = [
    ["fpsmove", "left-stick", "right-stick"],
]

[[event]]
name = "escape"
trigger = "button"
target = "button-escape"
action = [
    ["resetview"],
]

[[view]]
name = "main"
draw3d = true
skybox = "skybox"
ui = [
    "counter",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "update-counter",
    "movement",
    "escape",
]
