
[[texture]]
name = "inventory"
[texture.canvas]
width = 256
height = 256

[[draw]]
name = "inventory"
mesh = "rect"
shader = "mesh_pt"
texture = "inventory"
ortho = true
alpha = true

[[ui]]
name = "inventory"
draw = "inventory"
x = 128
y = 0
width = 256
height = 256
origin_x = -1.0
origin_y = 0.0

[[ui]]
name = "button-inventory-prev"
draw = "ui-rect"
x = 128
y = -160
width = 32
height = 32
interact = "button"
gamepad = "b1"
keyboard = "e"
origin_x = -1.0
origin_y = 0.0

[[ui]]
name = "button-inventory-next"
draw = "ui-rect"
x = 128
y = 160
width = 32
height = 32
interact = "button"
gamepad = "b0"
keyboard = "q"
origin_x = -1.0
origin_y = 0.0

[[ui]]
name = "left-stick"
draw = "ui-rect"
x = 128
y = -128
width = 96
height = 96
interact = "left-stick"
origin_x = -1.0
origin_y = 1.0

[[ui]]
name = "right-stick"
draw = "ui-rect"
x = -128
y = -128
width = 96
height = 96
interact = "right-stick"
origin_x = 1.0
origin_y = 1.0

[[ui]]
name = "button-escape"
draw = "ui-rect"
x = 0
y = -64
width = 48
height = 48
interact = "button"
gamepad = "b9"
keyboard = "esc"
origin_y = 1.0

[[event]]
name = "inventory"
trigger = "always"
action = [
    ["inventory", "inventory"],
]

[[event]]
name = "inventory-prev"
trigger = "button"
target = "button-inventory-prev"
action = [
    ["inventory_prev"],
]

[[event]]
name = "inventory-next"
trigger = "button"
target = "button-inventory-next"
action = [
    ["inventory_next"],
]

[[event]]
name = "movement"
trigger = "always"
action = [
    ["fpsmove", "left-stick", "right-stick"],
]

[[event]]
name = "escape"
trigger = "button"
target = "button-escape"
action = [
    ["resetview"],
]

[[view]]
name = "main"
draw3d = true
skybox = "skybox"
ui = [
    "inventory",
    "button-inventory-prev",
    "button-inventory-next",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "inventory",
    "inventory-prev",
    "inventory-next",
    "movement",
    "escape",
]
