
[[texture]]
name = "tex-counter"
[texture.canvas]
width = 256
height = 64

[[draw]]
name = "ui-counter"
mesh = "rect"
shader = "mesh_pt"
texture = "tex-counter"
ortho = true
alpha = true

[[ui]]
name = "counter"
draw = "ui-counter"
x = 0
y = 64
width = 256
height = 64
origin_y = -1.0

[[ui]]
name = "left-stick"
draw = "ui-rect"
x = 128
y = -128
width = 96
height = 96
interact = "left-stick"
origin_x = -1.0
origin_y = 1.0

[[ui]]
name = "right-stick"
draw = "ui-rect"
x = -128
y = -128
width = 96
height = 96
interact = "right-stick"
origin_x = 1.0
origin_y = 1.0

[[ui]]
name = "button-escape"
draw = "ui-rect"
x = 0
y = -64
width = 48
height = 48
interact = "button"
gamepad = "b9"
keyboard = "esc"
origin_y = 1.0

[[event]]
name = "update-counter"
trigger = "always"
action = [
    ["text", "tex-counter"],
]

[[event]]
name = "movement"
trigger = "always"
action = [
    ["fpsmove", "left-stick", "right-stick"],
]

[[event]]
name = "escape"
trigger = "button"
target = "button-escape"
action = [
    ["resetview"],
]

[[view]]
name = "main"
draw3d = true
skybox = "skybox"
ui = [
    "counter",
    "button-escape",
    "left-stick",
    "right-stick",    
]
event = [
    "update-counter",
    "movement",
    "escape",
]
