
[[ui]]
name = "button-newgame"
draw = "ui-rect"
width = 96
height = 96
offset = [-100,0]
interact = "button"
gamepad = "b8"
keyboard = "z"

[[ui]]
name = "button-loadgame"
draw = "ui-rect"
width = 96
height = 96
offset = [100,0]
interact = "button"
gamepad = "b9"
keyboard = "xx"

[[event]]
name = "newgame"
trigger = "button"
target = "button-newgame"
action = [
    ["newgame", "slot0"],
    ["makeworld"],
    ["nextview", "main"],
]

[[event]]
name = "loadgame"
trigger = "button"
target = "button-loadgame"
action = [
    ["loadgame", "slot0"],
    ["nextview", "main"],
]

[[view]]
name = "pause"
ui = [
    "button-newgame",
    "button-loadgame",    
]
event = [
    "newgame",
    "loadgame",
]
