
[[texture]]
name = "tex-newgame"
point-sampling = true
[texture.canvas]
text = "NEW GAME"
width = 256
height = 256

[[texture]]
name = "tex-loadgame"
point-sampling = true
[texture.canvas]
text = "CONTINUE"
width = 256
height = 256

[[draw]]
name = "ui-newgame"
mesh = "rect"
shader = "mesh_pt"
texture = "tex-newgame"
ortho = true

[[draw]]
name = "ui-loadgame"
mesh = "rect"
shader = "mesh_pt"
texture = "tex-loadgame"
ortho = true

[[ui]]
name = "button-newgame"
draw = "ui-newgame"
width = 256
height = 256
offset = [-160,0]
interact = "button"
gamepad = "b8"
keyboard = "z"

[[ui]]
name = "button-loadgame"
draw = "ui-loadgame"
width = 256
height = 256
offset = [160,0]
interact = "button"
gamepad = "b9"
keyboard = "xx"

[[event]]
name = "newgame"
trigger = "button"
target = "button-newgame"
action = [
    ["newgame", "slot0"],
    ["makeworld"],
    ["nextview", "main"],
]

[[event]]
name = "loadgame"
trigger = "button"
target = "button-loadgame"
action = [
    ["loadgame", "slot0"],
    ["nextview", "main"],
]

[[view]]
name = "pause"
ui = [
    "button-newgame",
    "button-loadgame",    
]
event = [
    "newgame",
    "loadgame",
]
