[[com]]
name = "button-newgame"

[com.rect]
draw = "ui-rect"
x = -160
y = 0
width = 256
height = 256

[com.text]
contents = "New Game"

[com.touch]
gamepad = "b8"
keyboard = "z"
action = [
  ["nextview", "main"],
  ["newgame", "data0"],
  ["newgrid", "world"],
  ["newplayer"],
]
