[[com]]
name = "button-loadgame"

[com.rect]
draw = "ui-rect"
x = 160
y = 0
width = 256
height = 256

[com.text]
contents = "Load Game"

[com.touch]
gamepad = "b9"
keyboard = "x"
action = [
  ["loadgame"],
  ["nextview", "main"],
]
