[[com]]
name = "button-loadgame"

draw = "ui-rect"
x = 160
y = 0
width = 256
height = 256

interact = "button"
gamepad = "b9"
keyboard = "x"
action = [
    ["loadgame", "slot0"],
    ["nextview", "main"],
]

[com.text]
contents = "Load Game"
