name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Basilico
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: bis83/basilico
          workflow: upload-artifact.yml
          name: basilico-linux-amd64
          path: ./bin/
      - name: Execute Basilico
        run: |
          chmod +x ./bin/basilico
          ./bin/basilico ./ build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
